name = "wayne-worker"
type = "javascript"
account_id = "YOUR_ACCOUNT_ID"
workers_dev = true
compatibility_date = "2023-05-15"

[vars]
ENVIRONMENT = "production"

[env.production]
vars = { ENVIRONMENT = "production" }
